### ISSUE TITLE
bug: local variable 'integer_value' referenced before assignment

### ISSUE THREAD

**Issue by milancermak** [FuzzingLabs/thoth#104]
I wanted to try out thoth on our code base. I got into this error when running `thoth local compiled.json -d`:

```python
Traceback (most recent call last):
  File "/Users/m/.pyenv/versions/starkware/bin/thoth", line 8, in <module>
    sys.exit(main())
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/thoth/thoth.py", line 63, in main
    print(disassembler.decompiler())
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/thoth/app/disassembler/disassembler.py", line 365, in decompiler
    decompiled_code = decomp.decompile_code()
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/thoth/app/decompiler/decompiler.py", line 194, in decompile_code
    self.print_build_code(
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/thoth/app/decompiler/decompiler.py", line 91, in print_build_code
    source_code += self._handle_assert_eq_decomp(instruction)
  File "/Users/m/.pyenv/versions/3.9.6/envs/starkware/lib/python3.9/site-packages/thoth/app/decompiler/_instruction_handlers.py", line 230, in _handle_assert_eq_decomp
    variable_operand_2 = Operand(type=OperandType.INTEGER, value=integer_value)
UnboundLocalError: local variable 'integer_value' referenced before assignment
```

Using cairo-lang 0.10.3 and thoth @ 9096f84

**Comment by pventuzelo** [comment]
Hey, thanks for reporting the issue. Can you provide your compiled.json file? Thanks

**Comment by milancermak** [comment]
HTH [compiled.json.zip](https://github.com/FuzzingLabs/thoth/files/10164938/compiled.json.zip)

**Comment by pventuzelo** [comment]
Thanks, let me know if you have any other issue!
